### ISSUE TITLE
Should this stuff be on display?

### ISSUE THREAD

**Issue by spences10** [antonderegt/mevn-github-auth#1]
https://github.com/antonderegt/mevn-github-auth/blob/0bb6e41d444dc3b3512fb59bc0a3e1262009252f/.env#L4

**Comment by antonderegt** [comment]
It's fake :)

**Comment by spences10** [comment]
😱 

So, it's included in the `.gitignore` if someone else uses it they will have to `git update-index --assume-unchanged .env` it?
